version: "3.8"
services:
  jenkins_master:
    build:
      context: .
      dockerfile: Dockerfile
    image: jenkins_master
    container_name: jenkins_master
    environment:
      JENKINS_OPTS: '--prefix=/jenkins'
    ports:
      - 80:8080
      - 50000:50000
    volumes:
      - jenkins_master_data:/var/jenkins_home
volumes:
  jenkins_master_data:
    driver: local

