version: "3.8"
services:
  jenkins_master:
    build:
      context: .
      dockerfile: Dockerfile
    image: jenkins_master
    container_name: jenkins_master
    hostname: jenkins_master
    tty: true
    restart: always
    environment:
      JENKINS_OPTS: '--prefix=/jenkins'
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_master_data:/var/jenkins_home
    networks:
      - default
volumes:
  jenkins_master_data:
    driver: local
networks:
  default:
    name: jenkins-network
